### ISSUE TITLE
\r\n not translated to \n

### ISSUE THREAD

**Issue by cpixelcube** [dannysmc95/computercraftdata#2]
When downloading a file that was modified with Notepad++, newlines are saved as \r\n, which aren't taken as actual new lines when uploaded to the actual store. A feasible solution is to replace \r\n with \n when downloading/uploading data.

**Comment by dannysmc95** [comment]
Can I ask what file you used that this happened on? Thanks

**Comment by cpixelcube** [comment]
https://raw.githubusercontent.com/cpixelcube/NoColor/master/nocolor

**Comment by dannysmc95** [comment]
This was fixed, please update

**Comment by cpixelcube** [comment]
ok, updating

**Comment by dannysmc95** [comment]
App store should update automatically or manually do it via pastebin/github. Please update the app with the code.

**Comment by cpixelcube** [comment]
I did :)

**Comment by dannysmc95** [comment]
Is it working now?
