### ISSUE TITLE
Store Error

### ISSUE THREAD

**Issue by 3dsboy08** [dannysmc95/computercraftdata#3]
I get this error whenever I bootup the app store:
store:181: attempt to index ? (a nil value)

Any help?

**Comment by dannysmc95** [comment]
This could be as I was just updating the updates as there is now a new version of the store, and I manually update the auto-updater which is just a web page, so don't worry, try again and it should work!

**Comment by 3dsboy08** [comment]
Now it is saying this:
store:178: attempt to index ? (a nil value)

**Comment by dannysmc95** [comment]
I think something is wrong with your program, can you re-download from pastebin, the new update is 2.3? Thanks
